replicaCount: 1

service:
  type: ClusterIP
  port: 19999

ingress:
  enabled: false

k8sState:
  enabled: false

child:
  enabled: true
  persistence:
    enabled: false

parent:
  persistence:
    enabled: false

env:
  - name: NETDATA_HEALTH_ENABLED
    value: "no"

config:
  netdata.conf: |
    [plugins]
        apps = yes
        diskspace = yes
        proc = yes
        tc = no
        idlejitter = no
        cgroups = no
        perf = no

    [health]
        enabled = no
