apiVersion: v1
kind: ResourceQuota

metadata:
  name: prod-resource-quota
  namespace: prod

spec:
  hard:
    requests.cpu: "1"
    requests.memory: "2Gi"
    requests.storage: "10Gi"
    limits.cpu: "4"
    limits.memory: "6Gi"
