apiVersion: apps/v1
kind: Deployment
metadata:
  name: pterodactyl-panel
  namespace: prod
  labels:
    app: pterodactyl-panel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pterodactyl-panel
  template:
    metadata:
      labels:
        app: pterodactyl-panel
    spec:
      containers:
        - name: panel
          image: ghcr.io/pterodactyl/panel:v1.11.11
          env:
            - name: APP_ENV
              value: "production"
            - name: APP_ENVIRONMENT_ONLY
              value: "false"
            - name: CACHE_DRIVER
              value: "redis"
            - name: SESSION_DRIVER
              value: "redis"
            - name: QUEUE_DRIVER
              value: "redis"
            - name: REDIS_HOST
              value: "pterodactyl-cache"
            - name: DB_HOST
              value: "pterodactyl-db"
            - name: DB_PORT
              value: "3306"
            - name: APP_TIMEZONE
              value: "UTC"
            - name: APP_SERVICE_AUTHOR
              value: "ynoacamino@gmail.com"
            - name: TRUSTED_PROXIES
              value: "*"
            - name: APP_BACKUP_DRIVER
              value: "s3"
            - name: AWS_USE_PATH_STYLE_ENDPOINT
              value: "true"
          envFrom:
            - secretRef:
                name: pterodactyl-panel-secrets
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: panel-var
              mountPath: /app/var/
            - name: panel-logs
              mountPath: /app/storage/logs
      volumes:
        - name: panel-var
          persistentVolumeClaim:
            claimName: pterodactyl-var
        - name: panel-logs
          emptyDir: {}
