apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pterodactyl-var
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
