apiVersion: v1
kind: Secret
metadata:
    name: pterodactyl-panel-secrets
    namespace: prod
type: Opaque
stringData:
    #ENC[AES256_GCM,data:J+Q3Tw==,iv:FK3h0K9qKqonwGEv1eOfqJzv9kGtEeoE/ET5e79fLpE=,tag:uRxRSSsaZeRfOb4lBGBaQw==,type:comment]
    APP_URL: ENC[AES256_GCM,data:H10YBPUri9rtlV4V1x4scxxRdk87hLQV70GkpNqmU7POxBwZ,iv:/mr9FzMo8w3owE+psUlbK/9MjSfAErgFxg1vEax/bBg=,tag:jtWdK1ld7mKacmatfQqdOw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:FDLb43GB8oYawA==,iv:y4FsnncmFn6wwtqNIsiCCgykJk7y78DbEdJPfCYXAcg=,tag:PiB2rNG/d9bAfYHjMpPz+w==,type:str]
    #ENC[AES256_GCM,data:fpz4lyI=,iv:INmP0GEIBsiNWTieJ74O1Ap2wz4pfzaCgsIxPddppBk=,tag:FDjMoP2SF90xTxbJyIyOsg==,type:comment]
    MAIL_FROM: ENC[AES256_GCM,data:f8rQTUrKRQs9K2uSEp2e/tPejLlWPcECAg==,iv:XVdXecO73aM6CuwD2ylw/ciowgY47JqzKNltu1DFtlY=,tag:ZpfXW1/vtYaXdhPSjOHImw==,type:str]
    MAIL_DRIVER: ENC[AES256_GCM,data:tTxNEw==,iv:yoM0dvjGWAMpUuNh1n+QpqZeOiGr7gTjKXBpxLAsCXE=,tag:ib60t6x3/E+ClUI9dZFlGw==,type:str]
    MAIL_HOST: ENC[AES256_GCM,data:DL9OH60yxRn3qTqzuH/cHQE9Uic+237aK6od3GYPJpzDUUoS0bsI5zrL52WW/w==,iv:4hZLk2N5cbL2aFFvyLk2xiT/bPmLO0oz9UCHxEw3HbE=,tag:IbPGFxGRgnqGusJIOvxFog==,type:str]
    MAIL_PORT: ENC[AES256_GCM,data:NUOp,iv:z6o0OE83xEhXihjUd72Lk86/i8JNNwKwu3/yIjd0pks=,tag:2LmHUkzVE9aLuk4sz9hzeg==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:ybb5I+C4utwFEwsbOYcFVmOLl8huTlBJKbmKu1T5x1f+5FZhpe8Int07sXulGPoQeWrlFpfV5PsG0uSW3sfG0UYcS773rek4OkQLXVHhmwmuE6/j+RJXY5Rc0Tg5S01bIqqL8HR1ok18mNAEBq7RZ0+J1Al3nx4vujKoDYp2U/II54b+tL4byDHI51CxqEpK7wqu8KP+kouQvYaRZuVD7KMaBw==,iv:3Kz1Oz6ZEstw8m5sCUjECSCnqHrE7VdVoSChty6vDHc=,tag:mPzLJqng3XihVndcqqasnA==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:Q0bUKuipJs5Ho98dv71yC+YCAEI=,iv:tKTSrEPj+3ydz1KEYVi7QCANTB2S6+Wqed04z5pK7Wc=,tag:YejBdwlmIIpFsyo7pzXRdw==,type:str]
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:v/ZNxw==,iv:OVrA3gdAo6P8n9XNaP8ieC7rKAhurNBYMUrxidt9bBc=,tag:JUagOBARkwEJbCTJXgIcGg==,type:str]
    #ENC[AES256_GCM,data:moan,iv:2IsE/uI1N66+Zd/C/G7zbM7X3KHIcNvrlVo/xFOyi+U=,tag:CJRqgIK6H08V6slp5egmwA==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:UDiYtCi7EQZWB/+PzXQabHlySfEN0clKxaP7wiSsPlw=,iv:tK4ptmXIJPzjVPjf9QOfrhnUtI7yNAL2mjRVE7mncJI=,tag:DphaGi1NTr/5L2JLArhXVA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:78dvFbPShZLUfpvALJxeI8Bl6fzguthjn56riCU+eSj9BHoSJEDTX1j+pBDRUT4y0a5VS50bTvsR8bf3oTHpLw==,iv:INbALIHDTwJc+EFp5YaqUVSwQbBPpmEe/elMPosgnWE=,tag:PwhIJYpyNGm0swT1xRMO5A==,type:str]
    AWS_BACKUPS_BUCKET: ENC[AES256_GCM,data:9bIM7iioxZI2jzCVRaWvENrlJg==,iv:rTbQ/H8B5ku4SWVB9aWsIDBD0AW/qzmFxe098YcMtys=,tag:v20aWm207T7U0Qj+pb2pyQ==,type:str]
    AWS_ENDPOINT: ENC[AES256_GCM,data:r/4BqIuVOb344HT69YOa5zHlDmxdiLYPAYvm8GISEzTMPaVsxVN7HxICHLypsStfU749cA9Uwxj9qHmSzcIbHcE=,iv:EIQU4JFtgYh9C83p0mIxNCnUlp7SQ6FTxa8+yocobK0=,tag:MgouIffV3b7fTmF3qOaT7g==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:NhyC+w==,iv:3MHejc7MdTmOXaRtOIHekY9sTG/UQSPdvhI2uIXzebg=,tag:y6GqNBuXn8c6/oe1xnZs5w==,type:str]
sops:
    age:
        - recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOXVDVkRkeWsreFVHRy8z
            SExjbVMyN1NJNlZFQTlhV0VoYWllclVoN1U4CktwMkVIc0E1L3RGSEZUR0ZMM2hQ
            MmZZb0FTOXN6a2VScWZFc0FhdElqVjAKLS0tIFJBYm1rblZpenFaYnExUWFWZzZh
            Vm9HdVNQQ1lKZmM4TkNkVGpKN1RxMk0K2Jou2QLEkBOxeyREzirDlJBzBdLauDq2
            +Am8kHHu9E6pqkj9yEttbMNON8vfFCWx725j80/IKTgPKIZmLBxoxg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcndzdGlCS2JFNm1MWlVY
            aGJya0ZVWVVjS3JPaGUvSGFwSytvQkJya1I0Cit4Z1VWc056aUpxclpqRitURUV3
            NHFLSjc2U1ZzdXdFRkEwR0pIMzhSL0kKLS0tIDVwNmpJdzVuRnJYKzJrMnF6MGFX
            aHhaSHYxb3pxTm1mRys4ZzdsYnFMNVEKm/CS6JAyg0GBQ1kDtHVdwoBGKTm2Oanz
            ELdJ/hdmLDD/+TSEKsBygtvmhmpxuxDXg7Q0HBB5G4+l/fiOwaIFGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T17:36:59Z"
    mac: ENC[AES256_GCM,data:r95FijNJ4zbwCsbrgZRdyT6NLnaiV/pTTE4zWzEc/F95VMpuJjhp+/mJGJhPzFyBQuIbP+D8KWcbkj59+5mvyqLvWVWgFOtONA63MEEIAS9DXu4PgpCGBKl+zZnZEQYP3d1QmigR6cYewKUCNRlPTTBiVwra9lhM+7kz8I0vdw8=,iv:rtO3S/juf9yC+85gF5Z93VFQikv1tWJo//plL9avy5M=,tag:yKbfxeYYjfn3Kl/ZANkWYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
