apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: fluia
type: Opaque
stringData:
    GENERIC_TIMEZONE: ENC[AES256_GCM,data:AOSLICSM6s67wAVe,iv:6hFlE05vP8pjLIJ4rTFLIqBtzQUnQ2wd0u0FCgV9/OY=,tag:hVItl7G7xbmW1bmzhDrJ0w==,type:str]
    TZ: ENC[AES256_GCM,data:DYgqJeA2jZ0flMQI,iv:iDumK/20V4xNl53XgGnKFuqVeAEw8gUntwGBD6lVguU=,tag:5VPyoXHFxfVnJ4hkBTfGMw==,type:str]
sops:
    age:
        - recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWelBKcFB2UkdwdzE1eFdF
            bVhwdEllRzJYcVczb0w2RjllRXdtZWw0ZjNRCmF1NHhCUWZYVUk5Ry9wc0QxMXFh
            RG4yU1E5ZkRqOWJXMW93N1h5WTJHbXMKLS0tIEhSQUJodHZJWU5KV014akVKVVg5
            Mjlna0dHWm1nWE9zZmYyaFllcmMxcFEKz1npkDvrKFksgPUmBqyCkC/VgBc98Ku6
            yfo/prJdYpIEFRq0Pzi9tvKUH2eZAvwjb+cOQ7NJUWO3ZFp+XwrJmA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPR2RWc29aYm1jdzhPNSsy
            VG01S09MK1orR2tPMnh4VStiR3FOY3FjYXpzCmpEMVVDWWdCaS9haUlGSGdOZHc2
            cFQ1TlRmaW5lbEdwVVhYM0JsLzFLYjQKLS0tIDVHeWM1UllRVEhGT0JTNW5nbjF3
            T1d0RFpsaXBDTVkxVE5TL1hhQ1o0dU0KyOHNur2Fxrw9NIMkIdib4rbdAqXT9yOz
            H2bSwo58GBR9bL2Jt9/A7Tm5e+cWW5gQ7Sn9Z1hbD/jG22QcYZeOow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T16:23:11Z"
    mac: ENC[AES256_GCM,data:vV1eqiFKceLrTpi2zyWqn+aShMGnw0Tnz0k/JIGrlvdzlwNptGoic43e1JqSB7U1FglZaxrE2XJe4++3GZv6j7mMaQarS9fLmVjWA16Hnbb017NyTV9IWTed1ASZiiJCGEHxO/ubTi3qoikd7X8lfwGhltZ1MjR7ir4tcAPv4Ko=,iv:5cyU5GuEi33/02zoGyGb/IdMG2C8yG+E2NiMty0BUbs=,tag:tt2oXhFNnwjiuMhquyvg5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
