apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: fluia
type: Opaque
stringData:
    GENERIC_TIMEZONE: ENC[AES256_GCM,data:AOSLICSM6s67wAVe,iv:6hFlE05vP8pjLIJ4rTFLIqBtzQUnQ2wd0u0FCgV9/OY=,tag:hVItl7G7xbmW1bmzhDrJ0w==,type:str]
    TZ: ENC[AES256_GCM,data:DYgqJeA2jZ0flMQI,iv:iDumK/20V4xNl53XgGnKFuqVeAEw8gUntwGBD6lVguU=,tag:5VPyoXHFxfVnJ4hkBTfGMw==,type:str]
    N8N_HOST: ENC[AES256_GCM,data:BCdGKWMZiEVcZXKK7ogOjl9cC1Lgek0=,iv:mhFtG/q39pH3guvrDVFXVuyxvdjyfUQUA2j/1ROJfxQ=,tag:OSsrr/ocI6snUjANHPXOCQ==,type:str]
    N8N_PORT: ENC[AES256_GCM,data:N+bz,iv:Yc77zX0l+vHdPbiA3qcLoDAdDzJ1HQVXx1vXodm8pEU=,tag:DNFR7regmtxSWGGzcYSRDg==,type:str]
    N8N_PROTOCOL: ENC[AES256_GCM,data:Sz9BI0Y=,iv:S1KJO5EL4AvemY8y9xwB+d/4Na6loQAVN6Gb3cRtAQA=,tag:bfFmpJx5Rb9ipYVma0EV0A==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:khd/N6jOB94RDw==,iv:fCrWbyfjPsGuXvM245UBecSWVyDosqv51cNEC/506fM=,tag:CoiimvfRiSHtYVTKRsxDjQ==,type:str]
    N8N_DIAGNOSTICS_ENABLED: ENC[AES256_GCM,data:IDjrrGs=,iv:GQjl4x/j6JBNeVGJFOUohBhkOlIVvZGrpXiJ2RpGExk=,tag:Z60ju/Vp0JMrqApagfHhvQ==,type:str]
    N8N_VERSION_NOTIFICATIONS_ENABLED: ENC[AES256_GCM,data:AnEkqvI=,iv:qnaG2qnQY0ZtbnEo+CKiSc/Ub5QTodQtzWhhme7PO9M=,tag:T2+9Xs64appxbqnYoxOKvw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWelBKcFB2UkdwdzE1eFdF
            bVhwdEllRzJYcVczb0w2RjllRXdtZWw0ZjNRCmF1NHhCUWZYVUk5Ry9wc0QxMXFh
            RG4yU1E5ZkRqOWJXMW93N1h5WTJHbXMKLS0tIEhSQUJodHZJWU5KV014akVKVVg5
            Mjlna0dHWm1nWE9zZmYyaFllcmMxcFEKz1npkDvrKFksgPUmBqyCkC/VgBc98Ku6
            yfo/prJdYpIEFRq0Pzi9tvKUH2eZAvwjb+cOQ7NJUWO3ZFp+XwrJmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPR2RWc29aYm1jdzhPNSsy
            VG01S09MK1orR2tPMnh4VStiR3FOY3FjYXpzCmpEMVVDWWdCaS9haUlGSGdOZHc2
            cFQ1TlRmaW5lbEdwVVhYM0JsLzFLYjQKLS0tIDVHeWM1UllRVEhGT0JTNW5nbjF3
            T1d0RFpsaXBDTVkxVE5TL1hhQ1o0dU0KyOHNur2Fxrw9NIMkIdib4rbdAqXT9yOz
            H2bSwo58GBR9bL2Jt9/A7Tm5e+cWW5gQ7Sn9Z1hbD/jG22QcYZeOow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T23:04:53Z"
    mac: ENC[AES256_GCM,data:ep6PWVGzdtxmDavBp+CjbE4q4B4jjf6M9GnairlHMgQhcZVoDAUvdmYhOZr8yFbtkGDSTco1wHZDOT9RfEzgitP6ZpIDFMJ0P5squKOvVPLwzA4dHvtCEf+7Lllm8aBcr94qHXGK0H5468pqTSexZnxBMcn8YuLDzQ714P3sOls=,iv:iWCim/eikhJKXPjo8tDGKrrDsp8Dpm50BEMYvC0Qpvo=,tag:z73ywJ9cr4a1IADZr04OhQ==,type:str]
    version: 3.13.1
