apiVersion: v1
kind: Secret
metadata:
    name: jp3d-web-secrets
    namespace: ynoacamino
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:1EZLDGMsLfTE6Y9Ufwrhpm8N/L4U,iv:XAXACKD+NB/zhTHGKvbA2uvRVM2GTqrsI3HbPd66Jvw=,tag:DH1LssgF+1oVFxU6/Gddog==,type:str]
    PAYLOAD_SECRET: ENC[AES256_GCM,data:sJEnqffcEgfTrbX1OpAOWAxFZGg=,iv:HykKfic/gYXR2T8Xa9UsclZeJ7k4MeGzplf1WKmvPJE=,tag:0Clw4vLbMBWGjNF15Wjt6Q==,type:str]
    SEED_TOKEN: ENC[AES256_GCM,data:2Rz7VmeTYelmtS4U5OJe6Ib6yys=,iv:B8boGs0x8eXBalxte3MXBKM+Ore8Jl7p/VH6wmOIx3o=,tag:Vr+qt57AoYjJYh3ZsQmirg==,type:str]
    NEXT_PUBLIC_APP_URL: ENC[AES256_GCM,data:qtf2c7rog4x7h8u/sG1HWYmSiIiO0haSaHPH6W5e,iv:YnIPl295MQlM+/QOfN+b94gZE0WwCTUIzj4wm+rEf2o=,tag:U0oj/olhFnExgcJAwcubNQ==,type:str]
    #ENC[AES256_GCM,data:+XAJS0nXvbILh9yHj0GQQadsFZnQ2jQ=,iv:rVoO+Bt5mqsDQYJ3ADiUpdh0kQou09MRzOmV0Db9/ds=,tag:/1PfmFOrROOSiXWQ8tEytQ==,type:comment]
    #ENC[AES256_GCM,data:gUVPJ7qR0CNOBBQtll7hrVca,iv:w/4FDhVYVxLj7gzj+3pnZZY/iEekR0Oe1JoF7GQHFUc=,tag:6yLR4neYqg1ILn0JiP0ceA==,type:comment]
    #ENC[AES256_GCM,data:955BIn8cnZ42j0X6CDBKUyUuFuDmLQ==,iv:8bsbeqh27DyrrfMiHHygzWE0BEO8IK0pasfGoV7jtus=,tag:FCE/CtRDGO5pCPzwsR89XA==,type:comment]
    #ENC[AES256_GCM,data:5dskcL58p5RStukW+/xwRovvZYn7Ow==,iv:sC+m2SAHoonUGImkazdf0d5GcTNSU53EgPxeVVr/KK0=,tag:JYiIQaTmVWmrGhWAuh+B1w==,type:comment]
    #ENC[AES256_GCM,data:VWgr/ViH8HfJ6bI52Q7HgI4T,iv:E0y6EvsmRM+BAO7XnTDvcie66kDUmMrlb+sQ+9l/xYs=,tag:uDA1kCV5OkzJ7LG9mJtZMg==,type:comment]
sops:
    age:
        - enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cWpNZDlDZFRoNExQUU5G
              U0xVMGp5U3dscVRJTTJrWG1lT2dEemVqRGswCkRkem1IMzNxd3dWUC83QVh1bk9U
              d29oYlZaamZGa2h3Ui9rbGtmQ2Z4aWcKLS0tIFBlK1NRWUZHNDJ3eXN2bGpUZWhT
              czRpK1VXd3NtNSt6NjduT2pPMnJhQzQKyuIM03Md8uHSFysK9GmylN2eTFqEYHNV
              JFvihq3crfKaKHw84k0uqZM+FCbSS/fKXk9V+OpCeN5o0f5lOOTYOw==
              -----END AGE ENCRYPTED FILE-----
          recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
        - enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaFdZK0piUEFmL01POE1v
              M1lZZ2tscE5GVE5JWS9KeCtEdVExbmhKNTNrClhLbjEzZmp1Y1hEN0dwS2ROZVEy
              aWdNQklkdHFZWjBkckJiSEgzK2ZnalkKLS0tIHZtRmg4dGZtR0I2NVQzV3psUVhn
              Um1kTmNkR0wzckJaT1lLbEtNVlZYd0kKa9IRMKVec3g/sfsWbhzKP1+Z/VRk03Is
              GcOeIp9afXj3e3lOioynjN3GZt8YDYCnAkf0GzWHVZpb+SjL8d7kCA==
              -----END AGE ENCRYPTED FILE-----
          recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T20:37:26Z"
    mac: ENC[AES256_GCM,data:XsAV3BoOZFnv1bNSFkYMrZwIY66Y/OArJh+X/NmdyCMmqnlgfLDllQCyM86SWam42vaVbk2u67N7XRJWxEUrOLvTnShJYSAqKAAdvlHywizxu+2dorlrxDs4clTI2Z5JH2nw8c4QaXoS2im+e8VHoYSEwrc6l11jsL0eUOkj/h8=,iv:oz9mnMdsgnfsynSCgbq7ZgcoVi2x4lBWpgF4Ev/sIHA=,tag:OJp/a1pItbpAwTTYExH61w==,type:str]
    version: 3.13.1
