apiVersion: v1
kind: Secret
metadata:
    name: evoapi-secrets
    namespace: fluia
type: Opaque
stringData:
    AUTHENTICATION_API_KEY: ENC[AES256_GCM,data:oTiVbPqmuNr+d/QoJBhODqehfyIpBEY006zVxaFyvvc09Kf/2dQTXuLOPb0jJdEEuserjjx1TGW/3j50/sJZ+Q==,iv:mgqrni1dfCBuN2TWpYFSXrWh0eFb4p3JSeuMjiutVy0=,tag:risWR+/O+BgsJyV/mC8kiw==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:fHQZHJWM5ADC9Cmu4GrsnXpNn5fTDkukglGzvlgSg9tnJEsKpWFOunrumuiffFF7VsesD0YI8OJVvDLSVfP8Vg==,iv:dX0+SzVTcV0LpcweosAezfNBAC+AoCRxDWXqbRPTvXk=,tag:ChwT8IDgYIKGEbegbCMn0Q==,type:str]
    DATABASE_CONNECTION_URI: ENC[AES256_GCM,data:9pls7vBiHGZxebMElq5BYKu8l1JBOHwdN2NQXcIgpN/sADBp78uOYdA8kd9j10v0Ldu2Rf40Y5PiUfBcn88tS7J5e39KGAmF/96WnHjpweiihaSaI0LFU4u0PWiYlYZkEj/XPB4N5dZBFgZzzZ2o,iv:XrceT359TBOlqp/9owM2PXwNpnb3bmaGqIErJzci6jc=,tag:m3gtaBHQCOdQZA+CN7Bm4A==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:MOzG7iFaMEWp,iv:RcEeLAmVEIYx/ljkcJ7UaiCkat+gQ+LSOA+UfT/CMs8=,tag:h695L1oHJ8mZQRcdfflVPA==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:ailAHa8hCuDPcEzAt9kWSr8BJTDe1tT4mz7v8sYQkmHZrZjlDXUI80SiP78IJ7ccYOhyHCtzOsfJwpso+GwaXw==,iv:5nNW26Fs4mjB5XhlWePQoSBtgpAA09UwopaK5xFmgxw=,tag:QCz4w0/ujsdLt3to1m4OsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVTVIMXRUR1J6MFp2Vno3
            U1RhNFhkV1lFUENnb1dxSnJMRUsycG90WEZzCllibG5wUWxQRjRGN0F2QXlPanoy
            MGZkdHQ1V1JQTDNrbllyN0g4NmtXekkKLS0tIGVNeWVTQjRqQk1XU0xiZnRadElr
            Y29XbjhPYjB1YzZVeTd4MURxSFY4K0EKK1fHXykxiAxTQPXivydRoPGsdbKkqWF8
            s8Ggob8lrq4YyS0GOqqz/CFQQlwG6MI7GyheTEI9UYey3FAxccS0Jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaDh0TUhQSWsxN0I3QndV
            bGxZYTF3aUxnY25ZS1Z0d3ZqcWcwaDEzeGpnCnZzRzNFSWRlSVB6bisxY3BibEtM
            VWtBd0U0bW1SVUFGSnh1aUtNT09oSlEKLS0tIE8zS0VNdUkralBjUGNrWllDSVNw
            d2NnWXdaK3NwTDJMbTRGMHpHRUVaK28Kk6zK8+ELa6qiuOT9uL8tvKVMcmOcPlgR
            0aBj81mkf4Z+AUwEcMCIngM2Ng9RpEpstgntjj6Fzsf4ULMVDh7QuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWHlLclF6aDd4b29QaFF5
            TW5SSEUrQlVIOUFnQUwvcnFvTWhKWDZsUFFJCjNGZ2hma2pLN2xYSWxBdzJOT0Iv
            V2dOb1Q3VEUvR0ZoaEZ4Qmd6dzlBRzAKLS0tIEprZ2NNQUdXNExlRzhEV2h5MlRD
            aEttNVlEODBFRFpUWWhIVlMwdVNudW8KP4w/G9b0DYXwWai2q3Kf9F0CG1oDqpjJ
            mmuiDMtbgN0LZTHShng+6dw8NpIJo3MKnKIVptrL5tVF8NOAVnYBaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age179xlc7hrhzlzjatrfjr5a5puldkxqzar7k36409w2dxhh9rxr42q2745tl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZckx1TnVZbFU3Z3ErVnk2
            SXRtaE9CQTRqbktTNk5qYVQ2TW1VZGdGMVdBCkxKQUtYTGl0N0hKRkdhSEFFRXNw
            WExzYWlKWmJIR2RERFJSSXZrN25YWk0KLS0tIDczTjRLRVFCZmcwaGNlanBOZG9u
            a0NHWVNsczBMeU5jenpKQm5md3FNYUEK3ckp0PWC5zXDik4JFN2caWbNq8Z1jmQg
            nVNT61IjJrDFSUhYx5WSwDfdODco19z2RZDUn4XEwFe637ofUYv5Ug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xk55pvdly05kxl5sxgt4vmczalyw4vmzyrehg5ttqcjz8acvvg5s6nyval
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T23:01:24Z"
    mac: ENC[AES256_GCM,data:PKH4oJ/Xj51bPKU4L3hkms8thpfhh/U1MlMADCLWTZDZmcpdEm1KPYBk+Omg+8PIkrgw+Oxm3CffJAYdd5WRi1kuIL0wUdES1HER61E89usXtmpm4x03B7e13hCorlSnJ+Ty49wly9/9gx74l8vXcjjqX76dH0bawOMojXG2kOY=,iv:PMiexPq68bZOUINdGRsEXEcbRwDRPEv3pOihqn/4yLg=,tag:kXO2AUScOMaP/b/b8/Hrvg==,type:str]
    version: 3.13.1
