apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: n8n-pvc
  namespace: fluia

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: local-path

  resources:
    requests:
      storage: 5Gi
