apiVersion: v1
kind: LimitRange

metadata:
  name: dev-limit-range
  namespace: dev

spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      max:
        cpu: 500m
        memory: 512Mi
      min:
        cpu: 50m
        memory: 64Mi
