apiVersion: v1
kind: ResourceQuota

metadata:
  name: dev-resource-quota
  namespace: dev

spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    requests.storage: "5Gi"
    limits.cpu: "3"
    limits.memory: "3Gi"
