nameOverride: "monitoring"
namespaceOverride: "monitoring"

kubeStateMetrics:
  enabled: false

defaultRules:
  create: false

grafana:
  enabled: true
  defaultDashboardsEnabled: false
  service:
    type: ClusterIP
  persistence:
    enabled: true
    existingClaim: grafana-pvc
  resources:
    requests:
      cpu: 80m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi

alertmanager:
  enabled: false

prometheus:
  enabled: true
  prometheusSpec:
    replicas: 1
    retention: 1d
    resources:
      requests:
        cpu: 80m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 200Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

prometheus-node-exporter:
  enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi
  extraArgs:
    - --no-collector.filesystem
    - --no-collector.netdev
    - --no-collector.mdadm
    - --no-collector.bonding
    - --no-collector.hwmon
    - --no-collector.ipvs
    - --no-collector.nfs
    - --no-collector.sockstat
    - --no-collector.timex
  kubeRBACProxy:
    enabled: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
  serviceMonitor:
    interval: 30s
  nodeSelector: {}
  tolerations: []
  affinity: {}
