apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:zc3uczITP5gPa1ioQqJ9pjuXn//x7dwuQfsS+uHgCIFHjSQdGCNOwQ==,iv:94mkdIs+rQOlahzwfVvzLKZzaZEkNivcmgYsQhF4xQo=,tag:9RF6XZrwhznSC+GIuc+jOQ==,type:str]
sops:
    age:
        - recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5V1BQMEIyMHhIWW4yL2Rx
            S3llby9wbXFtbWdDTDJUNWJNYVc2QlA1TTBnCm1WQ0NLeGhyb0FJcnF6WVNNVDZi
            YW1wSFZkaU03SzFabDNTRlByWS9kRVUKLS0tIExya3E2U0syazYwaHJMQ1A4c3B5
            TnJTaE8rZnJic3d4cUFxWHJZLzkwMGMKyMEV8pkPQY3pPeqhP87ERqHlJuTOtvXW
            Lt4ctFDN1sbx+q6bEw+4Q52gInfArbsEFi9+1DrCDDQ/VcnvS9h0Hg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWitaQnVJSm1xcWMwamNW
            RHQvZ3MwT1BaSmdpWDEzcmVvdlQ2UHBlVDNjCk1VK3grNHhaWWQ3VzlwTVFOVWRq
            cVI4bkR1T0s5SkFOQlQ3UXE1TXhWMUkKLS0tIGRtQ3U2Sm9qa0ZsdXZhWWpOLzRk
            UVU0TCtGM3VvR0tMWW1Xb3RKemI0b3MK2cJAu3/HCi0Wuo6I0HVOzo7YPDtUJt5m
            K09YOtdX47/cthxwaXsvMhqPqy+i3wOYBQNTKS7f4Gj7gnKR/3o4ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T19:10:28Z"
    mac: ENC[AES256_GCM,data:Saly7rwqFx08t8svsom1hCBHHmVdgkAcyUwzCofCLyoKrhW8MnQRaTk3UI+Jff8igWKFZyq4BDG1PidEItvvPq9aoK7tKq+eKoAsLyxrvkB0o9mg0j4ZDa2l5PVMg10KcB2RDGDGTfvCHTlH8UPdKcmvmx4O17Hjgf499QNTeAw=,iv:KoSO2fDMHNm9PU7NQj6MgM5Yjy89BN6aH+G5AoqpEQA=,tag:7EcZEAUxrAylfoWJslzUjw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
