apiVersion: apps/v1
kind: Deployment

metadata:
  name: uploader
  namespace: prod
  labels:
    app: uploader

spec:
  replicas: 3
  selector:
    matchLabels:
      app: uploader
  template:
    metadata:
      labels:
        app: uploader
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: uploader

      containers:
        - name: uploader
          image: ynoacamino/ynoa-uploader:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 3000
              protocol: TCP

          envFrom:
            - secretRef:
                name: uploader-s3-credentials
