apiVersion: v1
kind: Secret
metadata:
    name: uploader-s3-credentials
    namespace: prod
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:aTYSPK5aaQyltUn4zxkJ6Zjusnc/Rn7eY7XL06c8t1w=,iv:cyzMFy8q+SGQKs5jIw6LM9UOf0Be1Fn/lo2OhWZUn9g=,tag:IWosNpXxkkjZFA88tVlzWA==,type:str]
    AWS_BUCKET: ENC[AES256_GCM,data:8FVFvHm0jm6T97cG5A==,iv:QRo+mRaE/ko2gZlrb7vkXTChTlIsX7CmP83mCmziPqo=,tag:UJbZT5A7+ywIlm223OvSFQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:CFrBxv9RVGZbgV/KevTA+kDvHKQ0I9hdWcLwUJ16AvABGpyxPpw7r9W6VmeXCJdVmx77IBp28kaSyQo6lrGZeA==,iv:jbmfjxO3zySHJYrC/KJaZ+4bWiKqMAqX4azsKPKT4MI=,tag:ktKrB9FZIEWZubwqGjEzxw==,type:str]
sops:
    age:
        - recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzb2hvaDJ1dFRUQU1sNnlV
            TWVQOXhDQWFjMGNwTlEvcjB2Sm4wY3hXa3dnCm0vV1JzSFlyQ0N1TFVMRHY4eVNp
            SnZROVBiaFZyWmU3Wk5HbytTVXZFMTgKLS0tIFd3NVBIaEFoaUx2NmxDT1cvaHpk
            c25UeUdrT29EUDFCUTBDWXljRjFibzAKk9DJconskmrX9NPnQcnYT3WVVueXsQsv
            tUVspg9uqcQpK68Etyj6hCvcmMSXMJkbkUKtm/HdXaSETxLgjiql/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxLzZINk1YMHJ2ekZDR1dk
            YWlRVzJObVlvaU03Nmx3TEdBdGxNZ2MrZVFrCkwvSzFVYzZsb2taT1d0RmxZYTBj
            WHJMWkYwbWhnY25oMmpjQmRnTXk0NWMKLS0tIE93S0p0SFlnQWhteVJpQ25hUTVz
            ZjZlcFJIY202M2Yzc3pFUm9KSmRVa0EKaumM11ykD2Q5xxYJFaZktL1N8vJ68pv0
            B7Yq/+22lIn5CQlxbYVIcEIR217aHc8EYoo7rxCg27q8Tp+u3Juilw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T16:08:38Z"
    mac: ENC[AES256_GCM,data:sNzv6wtOAIy6jzd6UIMNs+fvNf7lUV4LunSrP6SSoozsgFRuvltaonv3Oobbu4o2inSvEUOBqtaT7GIBHw0HpVYBnxEOHnZ38vBdPj8mPN5xj1Bl6OX3kUgux3MV5SoK955Z1zLzHpBS7/Mky5JdpZVwv0DFy86LeXQa+gaMw1Q=,iv:bck7zBomE0O/te+Y4pjFq2iDG8EZOt1cUcovK6yGhK8=,tag:gcV2FUF/83wRAnKkZuKwzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
