apiVersion: v1
kind: Secret
metadata:
    name: pterodactyl-db-secrets
    namespace: prod
type: Opaque
stringData:
    MYSQL_PASSWORD: ENC[AES256_GCM,data:RraGsbbYsfHTiw==,iv:YOBk7FgofUo+zdFFow24FgiEzUrRIdnMcbQ6X/8j6w8=,tag:2Mi8iVyojuUXMqXzOAgmnw==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:q4H5hcQ3cT2ZJg==,iv:m//Hg48QhWjF/gvpo3RAAyYpEHbraj9Zc1lMzrWOm8U=,tag:WWoVeUDnZF8QK/8IA5SjMA==,type:str]
sops:
    age:
        - recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aFpybEZDV3RkV2FGS2JB
            U2dpeW8xL2ZqNis5cjVETXB0YkpMRURtKzFnCnlkcS9jck5DR1dpRDVGTWhJWU1B
            cWo3aW43R1pER0FPMFdEa0JFZ3FpVkUKLS0tIEQ2eis4c045MG55eWRnN0dRbjJy
            UjZuZjJWaWNOQTczSEM4NzBrTlZ3eFUKkD+H20THXRzkiLHK5+ze/982CmDMd3uy
            qysLO6iQHt56tTnaGIwzmMR+wUM153K0DsmZAtHsyzEgNwKMVMiPug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSem8rcXV4cklSL1JqZDJy
            VURJVXdOZWFudkowaGc4cHdTRitva2FPcGpNCnl2MlUzUWw1RndQbmpYWllvdFN4
            Q0xCRWpBQTFlbVU2MjBQQVJYV0ltNFkKLS0tIHZlOXZJVmpuU3NwMGxvb1h6YXVi
            MnhNS1hTR3JvWW50OEJZRXZrWE9WSzgKXebCihJSlEFecRBe8GdgxMpwoee9czgG
            tNYztsFDTUsqwgH52cJuQh5+aG8yJE999I/0sttfaHrUadsm8ViVQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T17:36:57Z"
    mac: ENC[AES256_GCM,data:tskqfmslQ5b2z+qy11XlQKqK0OUDGLQI19Q6RHnMohhZZONTaKnrgYRp30pijHg4ZUa+S9P7v0vuIvCiHZCNLN/zoQ/kT71VETuM2Y5nl9WNU1H2pE2O/5jGGORZ+wSHVA8y+QYqR1Bt4csoGC8HTztdqqvrnAygHsB4bjkgRbA=,iv:EKnGCWz6VcM/yWHv+zlcDlz9SQNxmnOQVGM6NQ1s4xc=,tag:vlEG0sz9gkiky8J4mVAuPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
