apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-ente-pvc
  namespace: prod
  labels:
    app: postgres-ente
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
