apiVersion: v1
kind: Secret
metadata:
    name: postgres-ente-secrets
    namespace: prod
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:/bNzkY4t,iv:3AHZfK/Nf7sgFX5XYVHtWyqeA97t7gdpwWlkpTUY6Co=,tag:6gc9//WZ7hyybq4Msc3IIg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:lUmAj5jd,iv:77HQc2jvaFnF5gUpsuO9QAkWENWx8KQcPMMtfUQBfMo=,tag:5dzs/DWhXktE/M3ejndieQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:23mQTLpFjQ==,iv:8rXTdoJAMThceb48+JIi713k8Yss85dhO8VBMjPHBso=,tag:+lkvcPkK4JryCgzK77aBPA==,type:str]
sops:
    age:
        - recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSGpFdnVnOE96b3BId3p2
            SWRqOExvV0lrc0xjSHZPdFVPYklDVW9OY2hNCmgzdWYyUDdwdGIyUFYxWG1PWU9y
            ekdqaXJYVnlWenFUMUhlR2kxL3oyNzQKLS0tIFVrTjdkTnk5bU5tSEpLc0IyUW5k
            L0NuSmpYUS85aXpFbzF5MEhGaEVkamMKBowMR7QSiTBKBeXIAQ8ZxOrhcyBRqGty
            SpFaT1dSBBg4+Y2aWXo0ErKuqw8l7fkEuynB6Fg6hYMbZ/n0vXA5Ow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUXZ6aVBJbUxKSkpkcHZ5
            NnBpd2VJWEg3UnliVG9GWkpLYTBkUThKRjJVCmV2eXVDSmRYRnZJNTFLZ3p6N1Y0
            MmphTWVFUmwzVmZUZ2pFVWxWY1NSbWsKLS0tIHoxRVBoNXRibXIwaTlzK2NTM3JY
            aHp3WFFZQ3dGb1E1K0VFTWRteGl3bjQKqo5ck5ID8zaQyetaIMNL2ECru1BNMlWr
            9/db66keJri9YY54MFFcDGj7jIw+/1ulh2mtLQMc4u/5shdt6qAgZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T16:15:47Z"
    mac: ENC[AES256_GCM,data:ejqcSw4SHGZZH3HzTdbc0NMobhf0c/YdHbnbGl6W4c6TyZBREqWFnwPlMyvwa937K/9rHEHAHX8z1DbWBpKrRCLxGqOk5y/ye5UefHR+iEkuGIXgpRSJFn5T4+eq6pLWF3hGrTPRVsixwl9STwy4+9qJGavNcUhXYZtNaDwZyto=,iv:Lk5HMOL50jSiIJB7R13t/Ci3ySGjELNFPKej5snkZYQ=,tag:L6E6GWbxSF57FCxgZYe0aA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
