apiVersion: v1
kind: Secret
metadata:
    name: postgres-ente-secrets
    namespace: ynoacamino
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:9KMGTd9b,iv:KFVTsWtUSZgkhTy3WzgvRUPDX2OfjEDm6jof/eMOMk4=,tag:Bx34OVqj5LyJxT5vUIdkYw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:eFDzlvAF,iv:JFHfGhTWF3ukuPac1x2hYaNDZUJ83WE+BISICCr3RMQ=,tag:aorJKix1B5II7twLSAbxGA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:7B9LGdfYvw==,iv:toq/igtSdSHaG8br94JkJENYctjer7wEiDzOyYoW1Wo=,tag:e6J3T6BuSZQvzgzkmO5PHg==,type:str]
sops:
    age:
        - recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWUpsa3FJbm1HNERBYjNR
            QmEvaktkQXVxM0ZidUNRcndaRTYrVWh4TVVBCnBQNlhjbnlIRjJlYStPTzNoWjh5
            b1NHbDArcUQ5bkd4RVovNCsrVDdqUFEKLS0tIGZNWGZwT2EyZ3hFOFpaUFNEaFNG
            d1luWGNCUzY1NXhNeFd0VUs5bk1nblkKX9QX8c2kL8RdAZKtYzI5btQA8/4lMl3m
            SI4HAOFgRmWczbwv779sDX6BJsHY0ZmH+hKMrgh1AMCr8GMEzlF+Qg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRXUyZlJNUVQ3cHVFUTBr
            MzBuZkhQeVMwSk9IT05YQnkvM3BLc252dFdZCkNUZVNpdnBodjVpVHRmaG45Y2RY
            SFJaN3JuV1B3dm84N0k4Y1RmNElRb0EKLS0tIGI4NVhFQWxSdUpZU21uZ05vU08y
            QTZicStQK2xWRjA3MHMrOFI1bkt4UG8KHK1YvDQ4PCSLbxgHwCrK9gUP305byEUz
            wnh94SxNA0CTV6IM3tmQEr5mZVTVULFE+mPZVa1z0aSm4hS5H37iJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T17:33:03Z"
    mac: ENC[AES256_GCM,data:6sJCMbVF8ixIdI/hlhDbIPweQ4bmob3MA5A0hS/kOlF1IxkbhWdeUMI6R7U5WlYUA4YuewWBsnEkjkK/mWYfI4u0mbcR0tLpSH7B2YrUpX00PzaPIz3J9i3wEPNSLPnBOx6KRJj49gG3u12yHQ+28Te5C7ZLTsoBGtrBd3EJCPo=,iv:SQhtopJ+Qq82S4z9/M+QSp0KWSp8ArAv/WOCFnH0uSc=,tag:dG39pFGMATg3Bn9CrlN9vQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
