apiVersion: v1
kind: Service
metadata:
  name: postgres-ente
  namespace: prod
  labels:
    app: postgres-ente
spec:
  type: ClusterIP
  selector:
    app: postgres-ente
  ports:
    - port: 5432
      targetPort: 5432
