# Temporary plain secret to be encrypted
apiVersion: v1
kind: Secret
metadata:
    name: vpn-secrets
    namespace: prod
type: Opaque
stringData:
    WG_HOST: ENC[AES256_GCM,data:f6hQbffokCXDyTQH,iv:mK/jhAb1Hj02Sm3CxXAGS8NRcx8LY9056+bUfiSlZt4=,tag:2IxO+5rhWfnD+CnIjiYPiw==,type:str]
    PASSWORD_HASH: ENC[AES256_GCM,data:f+he381bcU+5XvtrcvUw8GAWsyHNmH7KsjAx9K3lRof9lCiZPJ1gjo1xH7Xcgl4h8Pdsm5578IdtJq8X,iv:h8GhNHuGwKATHMr+hDuf2gxX0k3aTB4Mxu5KaDwuF6g=,tag:KImDxsp/KfBrO2n4vaJ5SQ==,type:str]
sops:
    age:
        - recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2d2hzYlBQd0dRREJjcSt2
            aVlXZGxscjB5QjZSNVo4VjZrdllCQ3FaWGdJCnVuMFk1UUNPSVpFMGZVWDdDOS90
            dTRyWDNvRXFZL1JaR0puSFg1ejFyMTgKLS0tIGEwZ0NMY3RuSTZFQnFXUTBzQUp6
            d2llRFVESDR5ZkdFc0xua2Nvb2FaM3cK7nkP9y5BbNSG6hKGo/bscNhBhpXK/dS7
            zvXt8/Tk2jELUJs/xtgH/ez/YVzus5DFjrClmiTbvqDqg1B1rIVooA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaVd4RnFaSjgwNmI3TFY5
            L3NHbGtqZUxEdmVCUDBUSkExa1psTG9vVFRrCk9YLytNNzVKSkhJazFYQWxvWDVE
            NE5kV0VkenhxSGsrRlVMZU1rSVhIQTgKLS0tIEpxd0tDb1dSZUQyQUU4UjdIeWxO
            SVlHOFY4UTFvU2RweFl5WGZmbVE4MUUKtbsb75V8zEKBFW2ebbHbJXjZ/4vWObQE
            Ll8kY8uOBVsqAR9KgAn7q/FjmIjB/LH5/ZbG72A6o7Kpn+kdYm6EBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T17:22:15Z"
    mac: ENC[AES256_GCM,data:0t1n5rFERIn8330j2xC62G/S6CQZxtVaBZ7pGQj/76Q/IyvqAi/+u9m4+AIT4d6HpMFVmZFvEAGbOL8cgfhSUVfJtv8LErMuAVZpVJ3vU1UcQbK5vjfyT0w9igGr4FXpK68a2HrZLIjictVcYrSAjVExe+Ic6Xt8FZ1BI2ZkW7g=,iv:JUFJVCQAjDvR6LK2B6ChIFvew6S0OkjFhBnbQyR7X6Q=,tag:qxFwJhjT4B8fXi1E9vAJ9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
