apiVersion: v1
kind: Secret
metadata:
    name: cms-secrets
    namespace: prod
type: Opaque
stringData:
    DIRECTUS_PORT: ENC[AES256_GCM,data:SgWUaQ==,iv:V+Dp6yRJEeNwDvhRM9ImfoZ8JWFG+wm/aeKhSV+upVs=,tag:X0Nab9lPh6DUg1KQJJ4hWQ==,type:str]
    SECRET: ENC[AES256_GCM,data:G/SrYEMwT1u2tdlVu3tl4nX+SDvcOfp8mRXv+wkc8JakVwzY,iv:vJFlDBkkbVV9LTl6Ux/yKMogdY6gvjLZS95QiWcNyKY=,tag:REj8WwEYSyJFE4UNEbnTow==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:MCMSTYE5FlB1BkkqonP/iM0XdQE=,iv:UE6fTTDCWvvHyO6kUAxp3FTkwEJgmrWl61ps/ze/41M=,tag:VcGyapnHOoPCH9pNN+RJ9g==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:qJhemv5SSOFhAQ==,iv:Wg85RhljjvYsFqhE3App7+ie4vOFDcJh/nrUHMYFhLA=,tag:OdhPrMhhUm45K0tu/kL+hg==,type:str]
    WEBSOCKETS_ENABLED: ENC[AES256_GCM,data:1KyfeQ==,iv:zRd1tyUyV76U+dGBcRTeeLf6cy82l9mDqI7y0dALbxA=,tag:xUfR7TaLN9ZHQwATmNtfBg==,type:str]
    PUBLIC_URL: ENC[AES256_GCM,data:7VEeDeh5j9yCcWQ1oD3/EauCVcnKQM/NIrkV2JRa,iv:RUqCFhqCEzovWu2ysB0UBunx7LXifLL44y7u1o1V9kc=,tag:kq6RwKPPWvln45WisHtpOg==,type:str]
    CORS_ENABLED: ENC[AES256_GCM,data:mSHf1w==,iv:x0FMGPifPYUjs5yk2u6xaEFW/qhuPoctMneilO3r+Nc=,tag:rEnQool9t/t2dTaaAcqs1g==,type:str]
    CORS_ORIGIN: ENC[AES256_GCM,data:2yk7U0QxaIvsRynY6LqxfC4+dDq0Wd9urDL3XsjWkQQ7/CAtPc+W0dI8LfMWmHTg8Xkk2g==,iv:QLAkYJMS69w/VESmNfZO282ZimaPtJTVV/v6oLzK4z8=,tag:TvpLE7wDt2FPvTtL8FvCPA==,type:str]
    CACHE_ENABLED: ENC[AES256_GCM,data:VLWxGug=,iv:C7QBCb5WHnSIV9Wji0NH7JyequtnVy4jWcz5/qaJk6I=,tag:kdUx4G2GSCg0mArhdYfsPA==,type:str]
    DB_CLIENT: ENC[AES256_GCM,data:GXRV6jkUpQ==,iv:Iw3TH04+6rSOt1ecPRiM6qAnOiUU8tTzXrfkPwlf1MU=,tag:PaEOr2ICdmbLfOmhaiBTfw==,type:str]
    DB_FILENAME: ENC[AES256_GCM,data:+YBsH6b+kx9K4z97Koy5s7XFsJvdrqDlGBk=,iv:ATS1I9/wVAJdmzMyUrtK0aZVCVyXk6gOkGctrLAAQNc=,tag:P4HcFzUdPAKiOW/4QEQWrg==,type:str]
    REFRESH_TOKEN_COOKIE_SECURE: ENC[AES256_GCM,data:VLnSyig=,iv:YqlSF6voEIEeRjmHBa+rHDHWlwAh39rNZVlxDf/sJGI=,tag:PjfY5rmADHnyf25aS9V08w==,type:str]
    REFRESH_TOKEN_COOKIE_SAME_SITE: ENC[AES256_GCM,data:cyFm,iv:MmE/lWG+FDYvEMbYNDA+gOc4i3SJOfkQse19tbwY/pY=,tag:rYyZfmLHPnE5garu8NGVmw==,type:str]
    REFRESH_TOKEN_COOKIE_DOMAIN: ENC[AES256_GCM,data:um5BZrwCgoVsbbpG6xeI0rApVlRAuA==,iv:QJZD+79Nop1INjEeg8g8AFOD0u+PhWr1AOECzdhAYaU=,tag:XM04HBkeEf3QlxhtBwaN0g==,type:str]
    SESSION_COOKIE_SECURE: ENC[AES256_GCM,data:BiipW04=,iv:975TDu8d2kV+GKp9OtgNjpQbLta/w7OhmpGnJkSvGvw=,tag:mYfDQZSXHxIjLHrAQE+jxQ==,type:str]
    SESSION_COOKIE_SAME_SITE: ENC[AES256_GCM,data:2Ybf,iv:ncgB4MZwHOv/HabmcwxmQIt+oybo+Qlr+bw3IOJUUTc=,tag:9tTD61sUNxKp175rSjImcw==,type:str]
    SESSION_COOKIE_DOMAIN: ENC[AES256_GCM,data:IPfsj0gTqmCnUG0Y0hoQ3KZpwNskcQ==,iv:Vjl+I2+lG4+8K5feRE/bZRlxH81wxKew5dV6mGlfYw4=,tag:IsJ9M9L6pB98bhu2T8/33Q==,type:str]
    EXTENSIONS_PATH: ENC[AES256_GCM,data:T+tCyakBl/BK2VaO,iv:qhEiFJ14t5mALQyQujyZlb5vIXqcFKpRW40oki4Du+s=,tag:TfJqr4DIG6kqyfQRU6gwfg==,type:str]
    EXTENSIONS_AUTO_RELOAD: ENC[AES256_GCM,data:58xEVQ==,iv:INU7mUn+/kC8zzMzc/9GCoIlAsDNidk3F9/DuYo2P1E=,tag:k7rzuNqGzIt2TniT2LH5tQ==,type:str]
    STORAGE_LOCATIONS: ENC[AES256_GCM,data:qDI=,iv:YHe54gNJ/qDzQ3XBACTlqAeyFtF5/zGtoyqzzURJEcA=,tag:Tw9umc1amCb7SDh6tXKkiw==,type:str]
    STORAGE_R2_DRIVER: ENC[AES256_GCM,data:dxo=,iv:A1GTG1hhYz8JYswMZmn0M+mFgck+rC54ENkwj+29rN4=,tag:SI+Xt1VKejqrt9HJ6iPaMw==,type:str]
    STORAGE_R2_KEY: ENC[AES256_GCM,data:ILTZW4EgZ8dMNmnMMQz7mVP2MejRjdh77feZqnajjFA=,iv:MIVXObwsebOumaaLViAyrYdqzDwVp7363Q/ERGpW+Rk=,tag:gnZzkR5bs/o2LgSNlEepZw==,type:str]
    STORAGE_R2_SECRET: ENC[AES256_GCM,data:8MsSeaPRAE6/abG5kTT93nLUgMhOiVYTtW8eY9Xy0T+CfTQEB8uQOuVS1IQNel1PzEBHvruz9G46ezfMPrpDJw==,iv:424y4Mkzxv/usIZYgHtEq9hrYE5fpdNDGAvp3wD7Yro=,tag:llZS3TPTs742/8bLS4Mtfw==,type:str]
    STORAGE_R2_BUCKET: ENC[AES256_GCM,data:xPzg5ryoFw==,iv:rMTDRf5WRcHzLke1Qbe1XTTXH/kNEHiINQW/F5JOlIA=,tag:mhJUmu52FGLA8fnvh54O2A==,type:str]
    STORAGE_R2_REGION: ENC[AES256_GCM,data:jpr8XA==,iv:GLKYNIxre0oh40EsUawfKJvnnzRYOGzZaOCH/xNOFDA=,tag:DU8gjQZvTRMCsjXyUfLKWw==,type:str]
    STORAGE_R2_ENDPOINT: ENC[AES256_GCM,data:CoRhPve1K1B2UBHgwvw86MsHX5XHMzG37Wv236xJ5a9yEoo7IuV2MZQ+LeZlV/oD7CCFBwq0R+kF8PVoNFC2V2o=,iv:fAC4qH9txc+Hc55N128JVx679KCxyReZYOlshaaaZP4=,tag:dAJklP0BHr5oywBt9EM+Jg==,type:str]
    STORAGE_R2_FORCE_PATH_STYLE: ENC[AES256_GCM,data:eWcWnQ==,iv:lS0lVafw7gueUKCtzdbR9FpiZ1864YOJvyjdz3Ea8T0=,tag:RYjWkO9KuUcFEQZR7M86UQ==,type:str]
    EMAIL_SMTP_HOST: ENC[AES256_GCM,data:niFNNKF8hcrf3PttD1UXsu5EQKyrEibnLw==,iv:leUEjAHyJZx2m86atnW24cXBE42GOvTtNlSimH3F+WU=,tag:6OwtQr0cuWBh+Uv1r7iN8Q==,type:str]
    EMAIL_SMTP_PORT: ENC[AES256_GCM,data:aXxU,iv:fBfl8Nn+vHPVdTe3fxJzZlR23Ueui1os6GV0FYwUiA8=,tag:POO9EIrBS5RTNYXsGbuvSw==,type:str]
    EMAIL_SMTP_USER: ENC[AES256_GCM,data:/SUgbVcLR9G/t8J+obhtddiwxKxZy0qxT6bJrz5RF8vajW3+2nUFWN9Eb4bSYfVipHZlXwCJnKVuWwFFALlAwF31PgRaJFKwthSaU9SUpfvfR6FGbvuJmEveLbGUVvnR8IspJs25PyCekmxQBWaYlWZy+bfIfHFrJ/j5duaMb/ENj91JBkN7WSNQBCB91rp55tSE1lvLe74pBlpLqXrarKG/5A==,iv:f29vkLYk+i+iXejdoX0n5QNFgLAFj7k5kP29guuOy1c=,tag:9e+r8bsGKDP2mDZMcFLxKA==,type:str]
    EMAIL_SMTP_PASSWORD: ENC[AES256_GCM,data:ScKT23lLkLgn/m0wntrOFTJPVgQ=,iv:EspshSrmjL+cQzRHUitvuFya2yHupfNNuYPolYa4E1M=,tag:ICPJy9CTsE2zll4CdnmUFg==,type:str]
    EMAIL_SMTP_SECURE: ENC[AES256_GCM,data:RpezlA==,iv:1V8/H6vBfghaydRiwIX9n7+iOOp9GAth+Cx3VMetfR0=,tag:TmErK2zvr1kZNhzpJuURDA==,type:str]
    EMAIL_SMTP_NAME: ENC[AES256_GCM,data:PaJZ/fS4WBLZdbg9oy1hmGn/djDJz6obvqBqVtxqIw7dGZp3LR2HjmXW/qFtJg==,iv:yjFaMOfq5zv+QcdWLiix9cFZ3O77J4T8a6TB9ZsYIwc=,tag:R5CV6aEhJ1r8cdBInksu8g==,type:str]
    CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: ENC[AES256_GCM,data:yGh2LPSJjdAT/HsKNfEng4nSzhCU8PvaI04IC9Izyfwxob7ifmQ9wPLJ7Nb+oLmW6hEJnd/hrviaIsiLzxutDT31LUWEntGLUkOjpfhJC1h/RsRwXK1D0ApioUvzZRGQ3ECq9LPUe+9N4WRfxEBNqfRUxMJzK3vMijcZpA8/cudwCC4BnSW2w2kYGaEw4Bu3Sf8x,iv:iF87PSC9iJhW+XJgL3gqwM4GVcPbDUVyF1TFC2B0Bi4=,tag:TAsluYTNTZ3GekVDBihfCA==,type:str]
sops:
    age:
        - recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzb2hvaDJ1dFRUQU1sNnlV
            TWVQOXhDQWFjMGNwTlEvcjB2Sm4wY3hXa3dnCm0vV1JzSFlyQ0N1TFVMRHY4eVNp
            SnZROVBiaFZyWmU3Wk5HbytTVXZFMTgKLS0tIFd3NVBIaEFoaUx2NmxDT1cvaHpk
            c25UeUdrT29EUDFCUTBDWXljRjFibzAKk9DJconskmrX9NPnQcnYT3WVVueXsQsv
            tUVspg9uqcQpK68Etyj6hCvcmMSXMJkbkUKtm/HdXaSETxLgjiql/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxLzZINk1YMHJ2ekZDR1dk
            YWlRVzJObVlvaU03Nmx3TEdBdGxNZ2MrZVFrCkwvSzFVYzZsb2taT1d0RmxZYTBj
            WHJMWkYwbWhnY25oMmpjQmRnTXk0NWMKLS0tIE93S0p0SFlnQWhteVJpQ25hUTVz
            ZjZlcFJIY202M2Yzc3pFUm9KSmRVa0EKaumM11ykD2Q5xxYJFaZktL1N8vJ68pv0
            B7Yq/+22lIn5CQlxbYVIcEIR217aHc8EYoo7rxCg27q8Tp+u3Juilw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T20:39:40Z"
    mac: ENC[AES256_GCM,data:Evfv1sI13wPuEcpMVOQ+rF5CQ6e5U4I3KM1j5exTebJZw38F47s8keUZKPoG2SwAmvuIC8IvNE5duVehklSjm75M+ut6OLTASXBmjuXUs1FudRyOdYLdAwHj9YlTE4hKfaHxOGuIYzG7uIS4IgHHqCYIPvdRjjQ7fFweisMzCQg=,iv:4mj1q3Ara7Oh5mdcY5ch12acWqMtnIkfpo9EDtNSxRk=,tag:MYbLjeLjhBfIbksDjtN+tw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
