apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: ynoacamino
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:Ev516Z+J59ApqKcNN3rP79wwLgLlxymmYHHQxFgsrf8sbJwddiBpyAQszDajeuVWeUS7AriJ9zUOZvEH7LLx1O9gBd0c37I/OPiedqAfRXIQoBTT3Ky3WlW481BqWrVivOtVtGU+kdIixgF5NjfHSHsJQRjXv78c2UyzwU9g1Hdm1jSEsS+uljqRjeIfOJWW41rwM10YLKtZFDYaDUrp3oKSlBe7yH1iPRqnDGNf6HU=,iv:H+BP9mrO9sRxtKiEI+Ocv3AcM/yDJMbg9G2biFOgcxg=,tag:5n/VAn/vivaat91gubXUWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWnFINDFYdEcvYTRNcVRO
            cC90bytJYXVNUjBEUnFEdGdzZ3pOY3F0L1JRCnkvaHQ5T1E5Y1Eva0dOdXN6clhR
            OUd6S2NSL2FoTFlQeWw1Si9EU0lxb1UKLS0tIDZZZ25qM1NHTjcrT2RoeUFyemY5
            TUJ0VTNHbGViZ1NrY3ZXRTBmdlV4cUEKtG3VhP/wbksC1SO+DPi6CByQeFBYyKBE
            +z90QiCmlfAJExdEosV9dN4wnCcwFMwaF/BdKZ/U/S8YU4L6XU7VdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTWVLVGxJMm4xZjBORG1E
            blJBbVpHWTNNU3FGVFFrMTRtRnRWODg1L2dnCmZDOVBTblVPTk4wbEhDVTJZcnpi
            Q2wwbjMzNzk5cWlGd1FrSTJ6RzFVY0UKLS0tIFJEU0t3R3FBUTZRS2xsV1Rlcy9x
            dlI0MkUxa1dteFk0bXVHR2JkMDBWcm8KsDJRnEAzw/NefTubRFCw9rCGJEVS4fIq
            T4A5q1zy3H1K03dz6U6S9lSZWPpq718fa7I5g+cak/vFaNWbfO1JYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcU5XZW10V3NFZVZOUkFj
            LzgwQVBySXljVGZMMnJabWxLWVQxdTBERzFjCi9idk1VTCtUNWtSK3JHQUFWK0RT
            SWpJV3lhcHZaMGVqTTFneUdOVWYrWUEKLS0tIHdobkJReFovRVRPMlRjN216YnJC
            U3N2K25QVkd4OFAyRDUxWHN1bG96bFUKZpgAhAZyDu+eXV5ganP0lsE2nrjTn8k5
            tsoSUP6601zpM2EG7fEunKZu2cUDUZchdQOp8JqdTSc5AbwYWqGmAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age179xlc7hrhzlzjatrfjr5a5puldkxqzar7k36409w2dxhh9rxr42q2745tl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQ1pqWjNPUE85dXF2T1g1
            SVlWUU5WSlB6elV0dmt0SVBsYWlVV2RDU3hNCnlRWjI4WEtjWk1Gc3UxaHZ4UTl5
            ei9UdHVQZWxyWDlCUEFBYVRFTDZIUlkKLS0tIFoyWUtRQ01zK1pwVXdkME9TS3Vo
            Q2hPeS9QeDVPZFBhYmNuREZ4eWNMWVUKFP4IhaspFbmLkLb61EVU5ALPE6OwMufV
            5JLVrvSPug+22KHJpKlpKVout4mWb5d5WxUGh00sUVUo8NxoNVS6Hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xk55pvdly05kxl5sxgt4vmczalyw4vmzyrehg5ttqcjz8acvvg5s6nyval
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T20:09:52Z"
    mac: ENC[AES256_GCM,data:16xFfc8tINNM05XUhKNVo4/yTNiDv5Vpy65EPEtHEtoNjMOW8Yu5Ly46viNhdTXz8uP0k5QdMoRL6bJfn8+D8enW6q9UuqE7ukET3QZluIX/h6cWeAxrw7JkTEQ5ht/+SmfWBGA8MMWsfh8IGYyHmMd1EPfTSN9uT5jDgp6UBr8=,iv:IKxPrKA80IJJO2/qY4MqvwTjNTZJPPUPsSkqoKlnSHE=,tag:1b5GAv7m8qKq0lOd3zwanA==,type:str]
    version: 3.13.1
