apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki
  namespace: prod
  labels:
    app: wiki

spec:
  replicas: 3
  selector:
    matchLabels:
      app: wiki

  template:
    metadata:
      labels:
        app: wiki

    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: wiki
      containers:
        - name: wiki
          image: ghcr.io/requarks/wiki:2
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: wiki-db-service
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: wiki-db-credentials
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: wiki-db-credentials
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wiki-db-credentials
                  key: DB_NAME
