apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

generators:
  - secret-generator.yaml

resources:
  - db-pvc.yaml
  - db-service.yaml
  - db-statefulset.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
