apiVersion: v1
kind: Secret
metadata:
    name: wiki-db-credentials
    namespace: prod
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:wRiEeA==,iv:DqlPftt2+ILpow0ti7MZuJJZigHaPDWGswqVUXxmFtk=,tag:80kBhJZtLN6w/QTrKQ/bjg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:cd5RdWGN3kxWXGX+sw==,iv:h5h9qt/W4g/pQU5zkj7aWB6Qz4fn/SZx22vl8P2KouY=,tag:wgBiDCj2tcu6oZL3PO6YXw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:viK8IGMPig==,iv:zTfdSL7Xt+7gXebZvpk7EIozQqRD5p+eWBA87XcNAto=,tag:g535I1BlxH1NTi2CnHf1tA==,type:str]
sops:
    age:
        - recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTjJsR0UrejFMU0NKQThj
            Mk1MS25qT3hMTGJyS3VLTzVjenpQM0FMR3owCkJIYjBrMEVmNS8vbW8zQXZFRVFQ
            TkxmZzZZSnRSb0E2bDBBZ1ZDUjg2WUUKLS0tIDkycE1ldksvN0x6S3dHY3hKVkJm
            OXpZd01na3Q3UXpQT2lSNzVDWC9CQW8KbfzlV5t2vWo1xP+ySRgVq8ZsgK0mcA2z
            CmwUdzbPUNENps+xl8xUzc62TIQ6mngagx28tqRCxMrQS14w/AE4gA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrN1FvSy80Mkt0bmQ5SlNL
            M3dOU3MxdDMwVVlDWUtaczNCMFYxMWxoaFRZCnAwRzYzcTVsRlpqUUZOUklLVkUy
            WW1QQU5haVowclBKT0hVWGlzT2loWnMKLS0tIE1aU2lKOEJJY1pTS2VvRk5sdDNO
            ZWQxZHlmTnNoQ25wUC9sd2lzZ2VxUGcKVSbwVCwVWezM+oaTuutEMBhaE36ZO/OU
            OndwLXfdsTDuyh78cPbvKiQFY0GztwBLA2goTD5ZvWH3ausalgy+FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T19:54:14Z"
    mac: ENC[AES256_GCM,data:jUhoMMo3W/ZFSwy7zvNNN9rz8S9yvqZMyO7J74IpQD0jaSGirJTrOsu24GNezn6zx2UOjEFo9jEJf+uYsCGRDKPBXPoxctYy69Pfq/rcIOJJ/Bq2wFQOH4lwULl/+1WCbOa8h922j+/GhfIVm5HO1bjPGErxjimxPQ6fJKrNUEA=,iv:c3JQ64a4nvwrfZxOp+BdDrsRf4zaOb/+4y7CMIkANUY=,tag:RStSDBhWJAo0NgTK9qaNlQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
