apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: hygacon-web-pvc-db
  namespace: ynoacamino

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: local-path

  resources:
    requests:
      storage: 1Gi
