apiVersion: v1
kind: Secret
metadata:
    name: hygacon-web-secrets
    namespace: ynoacamino
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:zC6zoeuox+sMiBauFhe3keEFnv1H,iv:HGEkdQQbySoKzmg6+mBSqba0C7I9BqiDBiQXwAcEES0=,tag:8lnFXQlieY/VpUMlUA5MZw==,type:str]
    PAYLOAD_SECRET: ENC[AES256_GCM,data:GPZVfqrQmHmTOWMBa5pVjfgAz0o=,iv:fD3aDjtFhGXylN3v98oAkVchcKE3Ez2HcqnWYmnX8To=,tag:tGL7e3LZlPGx5YerjB8yCQ==,type:str]
    SEED_TOKEN: ENC[AES256_GCM,data:AtrGW9T3RGn7eYIGvG9x5FLK0C8=,iv:q0vqyDOl4khA/nQ2k80OPvFj+JCjuQtQtMJwxM4yfYA=,tag:Ej5AE1gQhRNzjtyqoqdNLg==,type:str]
    NEXT_PUBLIC_APP_URL: ENC[AES256_GCM,data:uhp66OK2H7wqWSH9lZPUsCD1010PLe5QZ2wlsNOa3Cgd,iv:SfA9ya7ZTfWiJWV4pFm6XOYx8qTQ6Ob7QXdnroJoVm4=,tag:N1FraVFa5LVG3Tl7VIaJew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIV1lFc3cwVG05TGhJRllS
            aGNROEpXZ3I1R1R2OER3R2hiNnFENTR2dVdZCjA4RmlIMlE1eXh2N3Q4Q2I2b2Vh
            V2ZyQ2N3NnNtNUpUckNLR0ZjaHRPZ1UKLS0tIFlTWTdhd0FTODNJbGxjblJlb0lR
            bTR6M2lPQ2RjMHRnMUtzc0hyK1hrK0kK+3kwymwGo0CLHGAEE191fqoTh7oyunPh
            9YdYfCKGsY8p8Lan7LH0XUIVeRzFYXkR6gwEiY6Q50BpbR/lx8IVIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNjJvdW5ueUEzRmpuVWMr
            eHVHb0FBMHM3Y0hPZDNpczF4ZmlEZXUyN2tnCnlXb2prZUF3QndDalc1bnJlUWo3
            QTJKMlhOUmNUbkxCMjZyOWtTellYK2MKLS0tIEY3ZWpLMkVZc3JTd1dHY3NoUzMy
            N1JMMmE4RUwwSEdtVk1WT2orT3AzaTgKo4/fQCKkqEap/lcVHX8cBMlXMjaiY6lv
            Jr3OMF24gO1i2stYDIB7QE6lgcaqwS2noVxL2eIqpvk3KKjXElpCZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T20:25:32Z"
    mac: ENC[AES256_GCM,data:87G2ZMdf7owUHlJYbioW8vCha4ELCqLXhpiNmZLxpsjWKaT47YvD9EvMjywoXGFLbS2tffG539A8AkZCU2ZDgZSGsQB6Jxwjf9RneQb694Fh4R8iLEhf8YDcWR7lxY5WEWtgc1s6dhFuHfnY9EKBSrBr4zBsphWjU/Cv2cPVQNY=,iv:0kV1eUhNH9yAB/hUVZRF46WHguM0YSi6OCTGU1Ccnq4=,tag:+M9k7yHtzYySZIkV7d2Opw==,type:str]
    version: 3.13.1
