apiVersion: v1
kind: Secret
metadata:
    name: hygacon-web-secrets
    namespace: ynoacamino
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:KFc18et6mIclPQPwVEhSyF0UtiCd,iv:rtCoPexoKPLla/raV4EHXCg4B7gdcn/a0f2sPD2s69Q=,tag:YvXJG5XzYn+fU1cYQIBz5A==,type:str]
    PAYLOAD_SECRET: ENC[AES256_GCM,data:OllH5KWmpFEDK69lcaR/hLxFUIc=,iv:M09U2FjHE9UzUqHBTS9PgjNeCls0nM8tffg/dKa5tV0=,tag:4hZxQ8tH3XMvBVIls5vCDA==,type:str]
    SEED_TOKEN: ENC[AES256_GCM,data:rfyhfLtxxyIT/HfayBbhc7lgmC8=,iv:EgEy6nCocittOaJEBPkTs8qRg3EU7EjFTQkc+gj8tMw=,tag:3WpgehJsxUq04FYoag50KA==,type:str]
    NEXT_PUBLIC_APP_URL: ENC[AES256_GCM,data:/XjwMxsxPu/up37KOwGrnB9wQwUUR8LN5PRm1aqWrKxQUw==,iv:oM7ojIhvCcAn4U3Wx2YRZyaxNHl/a2rXykn6dHNztZc=,tag:SdoazLPptatvLTVCO6/RFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvczNVa3BGTG9iaU1hemw1
            UFI1eTlRUEFrdlJQbTJTYU1LVTZVcFRKcFFZCm9SaXA5ck1zWHlhdGtEaHljTXB1
            MUdwQjJyN1FkVFhhakhaMkw2Y2l6b28KLS0tIG1RektCYkFaQlNzN3VGcWZYZ0tI
            MHp5TGpmSUg1YlYwUEdibDJOTTFZak0KG/xqFQlaIZuDZzFcajn6SNgVTceUVwwq
            U4bvuyB8TFN9bd1TRcqY2URJmHHPYLZpadd6jp2s7nw3E+t7DFZmlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RGY3OFNVRk1mQlRkdlN6
            RjJwNjlNOXVhQ0xiTVZxNmFmcHdScC9tMlQ0CldJSEdwVGw1SFZUZFE5THM0RnRt
            cjc5UFlKK1RBT1RmUW9rT1FXanVqYTQKLS0tIFhoOGovVGNnOHpRSXM0cjBkU1Z4
            ZEIxRGhleWdTRVU1bTg0RXFrNkFxY1kKmjIme5CpB5aklPncf11oTzMiPVY4ZI71
            kF/BuTxqY2JTGZhShLMU+tCdL7/EtcQhATcq1ULYpRHU7Q7QXleSXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-02T20:03:57Z"
    mac: ENC[AES256_GCM,data:3PsDq4MVId8DPz7+gLP8891Rk/AWEd1UEYPqo2aByoEcbjUPjf56vd3c/coI57Vcp/OS/stqn7y3UIMam+LNMJBPGSJmsgFXS++B2NA9vYcAjzF47pnvKpWtJ4c2uBmvykuYSgwjGsrs1qOUOQwyH4zUmMC3mkG0aj0GHKH5IK0=,iv:aBR7kUTfMOX8OKZxaR4zQxKZX8/hn1nBZmBNSpzT4EI=,tag:MyyAyT9OHfLDXVTMNR1yYw==,type:str]
    version: 3.13.1
