apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: jp3d-web-pvc-media
  namespace: ynoacamino

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: local-path

  resources:
    requests:
      storage: 2Gi
