apiVersion: v1
kind: Secret
metadata:
    name: jp3d-web-secrets
    namespace: ynoacamino
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:1EZLDGMsLfTE6Y9Ufwrhpm8N/L4U,iv:XAXACKD+NB/zhTHGKvbA2uvRVM2GTqrsI3HbPd66Jvw=,tag:DH1LssgF+1oVFxU6/Gddog==,type:str]
    PAYLOAD_SECRET: ENC[AES256_GCM,data:sJEnqffcEgfTrbX1OpAOWAxFZGg=,iv:HykKfic/gYXR2T8Xa9UsclZeJ7k4MeGzplf1WKmvPJE=,tag:0Clw4vLbMBWGjNF15Wjt6Q==,type:str]
    SEED_TOKEN: ENC[AES256_GCM,data:2Rz7VmeTYelmtS4U5OJe6Ib6yys=,iv:B8boGs0x8eXBalxte3MXBKM+Ore8Jl7p/VH6wmOIx3o=,tag:Vr+qt57AoYjJYh3ZsQmirg==,type:str]
    NEXT_PUBLIC_APP_URL: ENC[AES256_GCM,data:595LqpojhNJx1jxzdRbRAakNkRgH0CCyKCec6Q+Kqg==,iv:hD/X9YBuFtHr55nYoKDZAVI9odau/Nh+A+asVzlhaL0=,tag:zfvB5gR0nqgBA1uoSVfTDg==,type:str]
    #ENC[AES256_GCM,data:+XAJS0nXvbILh9yHj0GQQadsFZnQ2jQ=,iv:rVoO+Bt5mqsDQYJ3ADiUpdh0kQou09MRzOmV0Db9/ds=,tag:/1PfmFOrROOSiXWQ8tEytQ==,type:comment]
    #ENC[AES256_GCM,data:gUVPJ7qR0CNOBBQtll7hrVca,iv:w/4FDhVYVxLj7gzj+3pnZZY/iEekR0Oe1JoF7GQHFUc=,tag:6yLR4neYqg1ILn0JiP0ceA==,type:comment]
    #ENC[AES256_GCM,data:955BIn8cnZ42j0X6CDBKUyUuFuDmLQ==,iv:8bsbeqh27DyrrfMiHHygzWE0BEO8IK0pasfGoV7jtus=,tag:FCE/CtRDGO5pCPzwsR89XA==,type:comment]
    #ENC[AES256_GCM,data:5dskcL58p5RStukW+/xwRovvZYn7Ow==,iv:sC+m2SAHoonUGImkazdf0d5GcTNSU53EgPxeVVr/KK0=,tag:JYiIQaTmVWmrGhWAuh+B1w==,type:comment]
    #ENC[AES256_GCM,data:VWgr/ViH8HfJ6bI52Q7HgI4T,iv:E0y6EvsmRM+BAO7XnTDvcie66kDUmMrlb+sQ+9l/xYs=,tag:uDA1kCV5OkzJ7LG9mJtZMg==,type:comment]
sops:
    age:
        - recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISVJmRzZLRDViNWh6WnpV
            OE5wVzNjY1pqaVBBYzJDcjI2anoxY2FERWxzCnp6RXh1YmJwaXpFT05hUHdFUjNq
            WHVCZ2IrL0NiUEJ1L2NyVzNySzhSd3MKLS0tIDJESjVrVHRDS3Q1bktlNUpXRFJC
            TUpHanU0bnJCSjROR2YvMWllRTNBTG8KBzEDwFx7N3gQ4WFNwYUxjstt2SlmzqV2
            fRyCLVqLPLpT9N5CVAdn/TI7WPZ2zX+U9EeixedJnGD4tnjJ1MKl/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNUhwbWhxZ3dkd3hpTWVl
            cWQ1c3ZFcm5hSG9mVWZHcEZJY0xkUWg3c3pFCk1IcmtqZE5kZVdjOFpPcWQrZ0U5
            NVZrczVoOTlFajlaNDk1TjdRelIzSG8KLS0tIEJMdnhNRmc4Mm5xRFFCcDRuZTZB
            Vy95OVE1dzI5UEtDd1VpMlFybTdRZk0KacdtQBYMzj8dWbo/npo7znG/1etRbijt
            yl/g/zXc8S1wecBGaXXn7dmcL72JGRVPq68zFgevAsN8ZOW2Jg2UVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T19:11:07Z"
    mac: ENC[AES256_GCM,data:/RQPblow+3NNld35WzpA+jeOOUUWBd9/NF1VdZ9PewKfXQej5N29yboPqouHB7qU9lUK6Pm/fiq2zXrn3J+QwvNDXHoIr0lybr6dVpIbIJ90GNrgoiIgjNqJJ3tyc5yzaXn66H1x0CKEVTY0TzzdS0YJkGsaok8/wfQl/cZF+xk=,iv:AGM2ICtOgvYrm+MlzuPlPiaZjgzyjZD0ESEI0Vnqh6Q=,tag:vmQVL5VrSrVkmTC0hGjffg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
