apiVersion: v1
kind: Secret
metadata:
    name: jp3d-web-secrets
    namespace: ynoacamino
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Kr//E3MdSmM791/74MjflQIsVY/E,iv:zJtC+wlqk/KbbcrfiHHajSTBHb7+Kv/seUXwkUJgE5U=,tag:tIhdRq84SN5jGpP3zFNDpw==,type:str]
    PAYLOAD_SECRET: ENC[AES256_GCM,data:AWkg6BwUWLrypUOgB7COwIRs9J8=,iv:nEOr2IcbtBrsIU2ywzbm4ue6GX2TPeE3yCk5TvDXojU=,tag:3b9n2y6d8TpDQOTV+tL3+w==,type:str]
    SEED_TOKEN: ENC[AES256_GCM,data:8yf+1S4vSodwc8xdvtRKnKBCcZo=,iv:HMRDaFTWd3HFAPDuk0R7a59A3HnSFjiHElaH1eXmOYQ=,tag:QXncS7vUOON9XOXMlC/4AQ==,type:str]
    NEXT_PUBLIC_APP_URL: ENC[AES256_GCM,data:TZ6iIuonuNKYIRQdQSKKfj0CgbV3O8OQzcKNnB2N,iv:cavfe2IdG0dMGd+oxCbCrmSRWuneCaudqEihyrL5OzA=,tag:td+agNh6SlZ/BTd946guyQ==,type:str]
    #ENC[AES256_GCM,data:7qXtgt/S6ztMQmXD+CiVxtxEW6G/Cp4=,iv:/Yh2MJooy+qOtxK6qh6y+FXPWQgrYBSYgXtSj6o5O/w=,tag:Rg3kaFjxa+Hgz4tRqqTUdw==,type:comment]
    #ENC[AES256_GCM,data:jokPR5Too9nXLt1Yc+587aNX,iv:Gl/LTPDXnw11aTUlsPBbGygKbGOaxo4vHlThfHLabaA=,tag:lsqpGREnrARYA7r3XfeFAQ==,type:comment]
    #ENC[AES256_GCM,data:6tZxJpOWV9Q8jRZqAQHQ0MaH6hJOvw==,iv:h6uRB1CobHDN4yyJnyPuMqcbt61XXB4IbyN/XgvHHnc=,tag:rHddV/RALOZdh5PRB1/8cw==,type:comment]
    #ENC[AES256_GCM,data:hC8MLOOZQJRci/Cco4rs0qpVJd4aJw==,iv:v84TKyyzPHxuNzCA5SmCMUyhM2ax9/yEXF9Ux0gKBZ4=,tag:qIG7meyJLYW2pkUwe3Hw+Q==,type:comment]
    #ENC[AES256_GCM,data:4Jf7+0icykpg7dsc30m5Wd28,iv:I+Ug119ryt9a2TwuNB0UPgPhyUp7PmWlsCEpadfdUxI=,tag:3DOy/FJnOYKOlWRyt4hlag==,type:comment]
sops:
    age:
        - recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cWpNZDlDZFRoNExQUU5G
            U0xVMGp5U3dscVRJTTJrWG1lT2dEemVqRGswCkRkem1IMzNxd3dWUC83QVh1bk9U
            d29oYlZaamZGa2h3Ui9rbGtmQ2Z4aWcKLS0tIFBlK1NRWUZHNDJ3eXN2bGpUZWhT
            czRpK1VXd3NtNSt6NjduT2pPMnJhQzQKyuIM03Md8uHSFysK9GmylN2eTFqEYHNV
            JFvihq3crfKaKHw84k0uqZM+FCbSS/fKXk9V+OpCeN5o0f5lOOTYOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaFdZK0piUEFmL01POE1v
            M1lZZ2tscE5GVE5JWS9KeCtEdVExbmhKNTNrClhLbjEzZmp1Y1hEN0dwS2ROZVEy
            aWdNQklkdHFZWjBkckJiSEgzK2ZnalkKLS0tIHZtRmg4dGZtR0I2NVQzV3psUVhn
            Um1kTmNkR0wzckJaT1lLbEtNVlZYd0kKa9IRMKVec3g/sfsWbhzKP1+Z/VRk03Is
            GcOeIp9afXj3e3lOioynjN3GZt8YDYCnAkf0GzWHVZpb+SjL8d7kCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-13T20:07:32Z"
    mac: ENC[AES256_GCM,data:lifBa9ofAkW+GWvWxdCF59SF+a6t9zI+ckekXGE9viPQB8oFEVuu7c7dcQf8TFUSh05lrjG6S2ZID8OuD6cH0ho17dkL3fSw540w3xs/V54gZjiXy70SCFSg85ld79JWd34V9dhGbU18BWyhUS+p0/mh2dUwFfAE/m+6N5M19bU=,iv:uzmSgpJtXuuMuJH36C+r5AkX9FJp3BFpwg1Zz4Z+WNw=,tag:dVg6oplm8lqqAZURyHLicg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
