apiVersion: v1
kind: Service

metadata:
  name: pvzge
  namespace: ynoacamino
  labels:
    app: pvzge

spec:
  type: ClusterIP
  selector:
    app: pvzge
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
