apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - secret-generator.yaml

resources:
  - namespace.yaml

  - node-exporter/daemonset.yaml
  - node-exporter/service.yaml

  - prometheus/rbac.yaml
  - prometheus/configmap.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml

  - grafana/pvc.yaml
  - grafana/configmap.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml
  - grafana/ingress.yaml
