apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:0XFugn0VSiMN,iv:HHbfIKhk91pJpVaF5dqhNQlHUXNbo1bQKy7apHUNKBg=,tag:bP4EOkVfAV/gMfy6vlJeVw==,type:str]
    admin-password: ENC[AES256_GCM,data:Fgx9jiHNlCmh3VY8xkydvGlmoY/TW+sX+uOH2A0RyZsXox0P4qEnsYPo9g==,iv:uoqn/wuhfz9Ar8n5CjS5mYAhejfktyevn6oOhBq5sVY=,tag:wP6xmZv+tu9KLJoYAGNaQA==,type:str]
sops:
    age:
        - recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Zys5WDVIZXBmcnBicnhq
            ZnVuU3FXOHVNZ0xxY2srVU5ZVEZ0ZVdJL0E0CkM3K3l6dml0UGhObmMrcnc0WSs3
            ay9rclh1MHpvdkxVc1RNZkJBUmJjcTgKLS0tIGlOV1VsSklQbXExTHRHWC9CTHJT
            dnE2UUVDWEZrT2o1cC90Z3E4MHg3cEkK/EXxlAc1isNkC4r46qqP3TeWda3r6vS/
            IC96294CsFfB+VXStULAOO1X30B6eAVd1d+rnonh+ZUaiDmsXejXyg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVEU1WEZHa1BWQ2V3TDV2
            b3phQzYxUTRaSVNUVUROZ3RBRjBlUFZhQ0ZZCnIzbWZsc3dhY3NQUWdPY3dwZzh3
            dnVSaFU2OUYyVCtySTJnQVo5aFo1WDQKLS0tIGtRVUl6c2N2ckdzcDRZOURRMjJp
            R0lzbUU2WjRjOEg2empaa1RCRWMwdm8Kc4sZLEIdK1BUzQSGgdcRPAio8RVnmzxF
            NftFPvsCStMx7J1VX5NiSwFGsQQhTUIY++ZFgYgpnCf0e9Kq7E2QhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T04:22:27Z"
    mac: ENC[AES256_GCM,data:1/8dx9TKMcOMR0XYNTLFMDQT81dT3hwWYD+1Ah/ONOcTF+A6KCDc4l05AiVNQ89okMDZjczNV4TyTux61BQ/b2XxE37h5mQrNBHIlHHi0ZfeHZ3LeCiYHVC9kGr1dJOdNICXZoRuAG5z3vRnWxVoXxqeE8GMjxbjkUL2l/K8s1o=,iv:2pPSMNDsSMKwrus/Cinq1WhpLvmIKcuCDjWh8tR1vb0=,tag:XkRQwYkCAFKdJgaCjXYXBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
