apiVersion: v1
kind: ConfigMap

metadata:
  name: evoapi-config
  namespace: fluia

data:
  SERVER_URL: "https://evoapi-fluia.ynoacamino.me"
  DATABASE_ENABLED: "true"
  DATABASE_PROVIDER: postgresql
  DATABASE_CONNECTION_CLIENT_NAME: evolutionapi
  DATABASE_SAVE_DATA_INSTANCE: "true"
  DATABASE_SAVE_DATA_NEW_MESSAGE: "true"
  DATABASE_SAVE_MESSAGE_UPDATE: "true"
  DATABASE_SAVE_DATA_CONTACTS: "true"
  DATABASE_SAVE_DATA_CHATS: "true"
  DATABASE_SAVE_DATA_LABELS: "true"
  DATABASE_SAVE_DATA_HISTORIC: "true"
  CACHE_REDIS_ENABLED: "true"
  CACHE_REDIS_URI: redis://evoapi-cache:6379/6
  CACHE_REDIS_PREFIX_KEY: evolutionapi
  CACHE_REDIS_SAVE_INSTANCES: "false"
  CACHE_LOCAL_ENABLED: "false"
  S3_ENABLED: "true"
  S3_BUCKET: evoapi
  S3_PORT: "8333"
  S3_ENDPOINT: evoapi-storage
  S3_USE_SSL: "false"
