persistence:
  defaultClass: false
  defaultClassReplicaCount: 2
  defaultDataLocality: best-effort

defaultSettings:
  replicaAutoBalance: "least-effort"

metrics:
  serviceMonitor:
    enabled: false

longhornUI:
  replicas: 1
  service:
    type: ClusterIP
