apiVersion: v1
kind: Secret
metadata:
    name: server-ente-secrets
    namespace: prod
type: Opaque
stringData:
    credentials.yaml: ENC[AES256_GCM,data:NNyh3mHoXjy2zwFicF8w0uQXNvl2bj+GEIUQO65hwlMC4vOB/V3ayVg4EQYaZjqBMT4I7oWS743L5fLx1gv/Xf6G99AklxvFFwGy66gsPW10UCRq43o3qbU=,iv:swJn4uzFhidLrHzvlZFdVtsjB/22mhB7uh18pLPPGYg=,tag:OID6GqEYREtiIRKy11uKwg==,type:str]
    museum.yaml: ENC[AES256_GCM,data:RvZEnSzVZFFBDD2uodxXiMQc240BMJUUD8of6bvvsxGp5EggWY61Kz2xaJ1wWSK0aFLNTbixSJ1sJmwU/3JCicTuOPmXu1HPE/We/OY3ezqFalK6kSKdg32h2nVZU0k3ZuuIwTBq48YtN8qm5973NGD5peiwrTXuoKjrn+W50XjqU3T5qI8dGMxrHiu25kMN1bw7OpZZs4JFA2+DoJ21tbVmoDHj+1eitptQLKavAxEwvMZLRf+mcebIOt9n9tXw42oAFXYZAbriPekw9NgPyiFPj8nb6pCxzzkZuaGbdnsNXN9eTfc2MtqTEQ4N0zI1FB3sTUJbSP6zUnnectycoOgHaKaB+yfdC6kLrtaP/ZttsJ0+WVz07KsAjdDxsrNbZu/46wzTbqtBLNUeFLorONI+k9DuEwI9RcQdDBwVwaWPsKx4GwZX4hbbuwnwucAlTojKSGh8RfKrv/ZCS9362F39DOmG2MsO3fUt6ZdUGRvsmoxGlXy/kmIZ,iv:MW68yNuVeYAvd0/hCs+eZA0KSJp8L5JYD8G2CB5sWQc=,tag:xYO1Lq3I2ZfV7AI30ZfKlg==,type:str]
sops:
    age:
        - recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWU1ua256ZDA3cnJoSmEz
            TjVTV05yME9mcS80dksyc1BxWU05K1FRelRjCk5ucmRrWnJJMkhOMmQ1b25PKzRl
            aU82djBkWEJLbUdKOWxDQ0ZuMlAyWFEKLS0tIEFLc2NLS0tFNHpHc2VldUtWS3BD
            bithVWJkZjVSTHpzNzVTQml1Zmx5SmMK9QGnFm+9SE1KJsRZEvsF7ALSlG7VNF5+
            sqLhIqOorIvx0qyVVJ38qzffgJvepf4j9eU6/LY1tUeFFSIOIRByZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQmlSOVcrODd0a1BhcFU4
            ODRualJaRUpHcDNJNHJMSjRrMi85aysrREJnCllMbTBCY3NvTEFjZkR2RE05aDIr
            Q2V1clRlMXBPS3E2OVA5Nm5IMU9jUU0KLS0tIGR3NEIvQ0JpRFRPMGRQaUx5QWVm
            bGlRRExNNEFVdGxGYWU4eDVuREtQQTgK9who4XcaPTdr0GkyypCKkLc8mUsifyyG
            96RTstDrFeP1Z4YT+Ur7tL+EdtF4W8im0IFXkbjf3QyhLCaO4NhF5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T16:15:04Z"
    mac: ENC[AES256_GCM,data:2CysF2LE0F11uRu0HabpYlji1jXkd8i4ugPaZCfwAUHj9KpmNylFgxkx7GlRY7ev7FTXCrU0nKH42Wd8DqCd5ZYxACI6tU4CWJTKRxe1wD1TgniosyE/y1WVBDzg43r4RCobcNjDqhTRz72rR1pdAcVkzHXswKjEc+Z7brVJ6iQ=,iv:9Gj1ikPQzZVMkcsvJgUvFK3GIWeVPGhRKCGluBc6KqM=,tag:bJIrF4ZnGX6t28fEd4E09Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
