apiVersion: v1
kind: Secret
metadata:
    name: server-ente-secrets
    namespace: ynoacamino
type: Opaque
stringData:
    credentials.yaml: ENC[AES256_GCM,data:jxt9JRkTsNbnowzU4sdi88LQkjo7whHjBYy4jbJT7liqf9E/uokN9F+kG/jX1wQaxKdhWH/zIKWCrFGnuSyQ2jMR/fcVG3ygk1gsgITP+9To5OqF/0tkvM4=,iv:Ab2VWmwTzEgwmwlWZhaVVoOzBO/qw8c1r+OF4mFKdBc=,tag:jM+LgyXUKCRxaGDgnn09aA==,type:str]
    museum.yaml: ENC[AES256_GCM,data:4w4C8aQCiY0mWzY7FnrQaEh3e03acDawylLylb+KeXILSbdgkdD9AWe/EPAMXFWxy/Vg8RHohLE4RXjXGwuE8/0/A15zdwhsBmzgMA+iYw1+HHg3PsdB1XdssaGLhYubs6AG1b7IsW31Z2eABEWKv06ANfxz2mAbAfEBW9HLPnaP46F7LEgoAw1Kt5bZFfXxcL/4T/9vW1wYtf3enT6q0pW8G8RzKXVjFZmfG/wWL9wyOddPUU4mdDsNF4nB9SP3ivIWsffDCxkGnmKnuQ/q2cbMvufUR0OomE938PkjuEIsL3r1C6XLEuw2TMMd7a+npp9NZKtmhGOVngYxl3mxoOL5c0dMLb1XlW9g58Ay4Qc+bNrYtYWr7a+svnmp0U4C2TZbYvY+PCWsW6QcQqeCklnfKrzptzFkTm8E7mUkjy/8N5tyCWDz7KMoaiSwDpHvIS33d2lMbf6d/w6kblp4KPxdPVRJizxND32vmF5lvkI8IBHsU4sO6vwH,iv:EelVn8VM2KeD5RZgTst4rVR6EAO1fRfaLgNWRM0ESAg=,tag:l6gdwD6yv6DfJoj/nBnyyw==,type:str]
sops:
    age:
        - recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRVhJSGJhU055c1NpRUp3
            MmpadUFNVWh1dTJGYW5xNmdDa3lNRncwRkZRCmVmdVg4cmowYXJjRWdici9OelNE
            V0lHMFhkeTR0b3huUFlOVGZSYk0yN1UKLS0tIEVyYTJvL3F2dHltNWNzSDhTcjhT
            b3M3S2l1U2pwRUxYUDl3OC9ZQmtvTmcK4zMQl0FwpeLaYXEeHgmy+BEE2NsMc1/r
            2DzrNl1JeVBsl7H95MdoS6QtxILihwKNmApgYAXhalS7XIoyesQffw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SDBkdERKVTFlaDAzb1RX
            bDJaRGsrRWlXYTBxeXN1SGg3RTZrYStpdzNZCi81ZFFRTHFsSXVhU0NYVTFpMk1C
            M0lZaEwyaEdvUDVGenl1ZWw4NkZiQjAKLS0tIHFrL1RDNWpmUDVqa0lYUjJkNUJj
            Tm1UMVQwcnRHN1pUbjB1SUVOVnZ6S00K4Zp6qKlpdrBLhRFGmR0tFcd/Iurx+X3j
            4WM290KAw1QnB4Cx1KYPEGtu445nPlBeKEEaQ8i/k8P66I1IS3QMZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T17:33:16Z"
    mac: ENC[AES256_GCM,data:L7lz6COwo7AQ9QilME9HdKqVVqmKSmk0c6NZ+tKrPIqALOcqI5Xfi1bZ1eKCU03h573PIpI+SPLUyDt66f3xdlGT9aIY6zK8/x2ADArT9eAh4ZlJtooZKos/nyUJCzR/a19MlsrIZpmy+QV0hJ49KFFUUIvIp/qybIqAEofX/zg=,iv:vcSUNxcB4MLfatFrfFQ10VpNRnnYzFR0KwKcFY9HzwY=,tag:XPKcQ8FFLMNYwm8gYeCjsg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
